import HeaderTop from '@/components/HeaderTop'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderMain from '@/components/HeaderMain'
import Navbar from '@/components/Navbar'

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import MobileNavbar from '@/components/MobileNavbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 
        Deve aparecer em todas as páginas, este layout 
        componente é de ordem superior que envolve 
        todos os componentes, todos os filhos, todas as
        páginas dentro dele...
        
        */}
        <HeaderTop />
        <HeaderMain />
        <Navbar />
        <MobileNavbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
